package com.lin.test;
import static org.junit.Assert.assertTrue;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.lin.service.Library;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
